version: '3'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
    volumes:
      - ./dbc:/var/lib/mysql

  db_admin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"

  omeka-c:
    image: vicding81/omekac:latest
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./modulesc/:/var/www/html/modules/
      - ./themesc/custom/:/var/www/html/themes/custom/
    restart: unless-stopped
