version: '3'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  db_admin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
#    links:
#      - db:db
    ports:
      - "8080:80"

  omeka-s:
    image: vicding81/omekas:latest
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./modules/:/var/www/html/modules/
      - ./themes/custom/:/var/www/html/themes/custom/
    restart: unless-stopped
